1. Please create two upper triangle matrices A and B, calculate C=AB, check C, weather it is an upper triangle matrix, especially the relationship between a_{ii}, b_{ii} and c_{ii}. order n should great than or equal to 6.

2. Please create two unit upper triangle matrices A and B, calculate C=AB, check C, weather it is a unit upper triangle matrix. order n should great than or equal to 6.

In [1]:
import numpy as np

In [33]:
ORDER = 9

def create_upper_triangular_matrix(randint_max, order):
  return np.triu(np.random.randint(randint_max, size = (order, order))).copy()

for i in range(5):
  A = create_upper_triangular_matrix(5, ORDER)
  B = create_upper_triangular_matrix(10, ORDER)

  C = A @ B

  print(A)
  print(B)
  print("\nC")
  print(C)
  assert(np.allclose(np.diagonal(C), np.diagonal(A) * np.diagonal(B)) == True)
  assert(np.allclose(C, np.triu(C)) == True) # Returns error if C is not upper triangular matrix

print("All C's were upper triangular matrices!")

[[4 0 0 2 4 3 4 4 0]
 [0 0 2 4 4 4 0 4 1]
 [0 0 4 4 4 3 3 1 2]
 [0 0 0 4 4 4 4 3 2]
 [0 0 0 0 0 2 4 4 0]
 [0 0 0 0 0 2 4 4 2]
 [0 0 0 0 0 0 2 3 4]
 [0 0 0 0 0 0 0 2 1]
 [0 0 0 0 0 0 0 0 2]]
[[3 4 7 7 5 6 7 9 5]
 [0 3 3 9 0 6 1 5 8]
 [0 0 4 5 4 6 4 6 5]
 [0 0 0 8 2 7 5 2 8]
 [0 0 0 0 6 5 6 4 2]
 [0 0 0 0 0 0 6 6 9]
 [0 0 0 0 0 0 4 9 4]
 [0 0 0 0 0 0 0 7 5]
 [0 0 0 0 0 0 0 0 4]]

C
[[ 12  16  28  44  48  58  96 138 107]
 [  0   0   8  42  40  60  76  88 110]
 [  0   0  16  52  48  72  90 100 112]
 [  0   0   0  32  32  48  84 105 115]
 [  0   0   0   0   0   0  28  76  54]
 [  0   0   0   0   0   0  28  76  62]
 [  0   0   0   0   0   0   8  39  39]
 [  0   0   0   0   0   0   0  14  14]
 [  0   0   0   0   0   0   0   0   8]]
[[0 3 2 3 4 3 4 2 2]
 [0 3 2 0 4 2 2 0 1]
 [0 0 2 3 3 2 1 1 2]
 [0 0 0 0 4 0 2 3 4]
 [0 0 0 0 1 1 3 4 4]
 [0 0 0 0 0 0 4 2 4]
 [0 0 0 0 0 0 4 4 4]
 [0 0 0 0 0 0 0 3 0]
 [0 0 0 0 0 0 0 0 0]]
[[9 8 5 9 1 0 6 6 2]
 [0 3 6 0 8 7 8 8 7]
 [0 0 7 9 1 0 5 9 3]
 [0 0 0 3 1 

In [30]:
ORDER = 9

def create_unit_upper_triangular_matrix(randint_max, order):
  result = create_upper_triangular_matrix(randint_max, order)
  np.fill_diagonal(result, 1)
  return result.copy()

for i in range(10):
  A = create_unit_upper_triangular_matrix(5, ORDER)
  B = create_unit_upper_triangular_matrix(10, ORDER)

  C = A @ B

  print(A)
  print(B)
  print("\nC")
  print(C)

  correct_C = np.triu(C.copy())
  np.fill_diagonal(correct_C, 1)

  assert(np.allclose(C, correct_C) == True) # Returns error if C is not unit upper triangular matrix

print("All C's were unit upper triangular matrices!")

[[1 0 4 0 4 0 2 3 3]
 [0 1 1 0 3 3 2 4 1]
 [0 0 1 2 4 0 0 2 2]
 [0 0 0 1 2 0 0 0 4]
 [0 0 0 0 1 0 2 2 4]
 [0 0 0 0 0 1 0 3 0]
 [0 0 0 0 0 0 1 1 3]
 [0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 1]]
[[1 6 3 4 1 1 3 0 8]
 [0 1 6 5 0 3 7 7 2]
 [0 0 1 6 1 6 7 9 7]
 [0 0 0 1 1 0 2 5 7]
 [0 0 0 0 1 5 2 0 1]
 [0 0 0 0 0 1 0 4 2]
 [0 0 0 0 0 0 1 2 7]
 [0 0 0 0 0 0 0 1 5]
 [0 0 0 0 0 0 0 0 1]]

C
[[ 1  6  7 28  9 45 41 43 72]
 [ 0  1  7 11  4 27 22 36 53]
 [ 0  0  1  8  7 26 19 21 37]
 [ 0  0  0  1  3 10  6  5 13]
 [ 0  0  0  0  1  5  4  6 29]
 [ 0  0  0  0  0  1  0  7 17]
 [ 0  0  0  0  0  0  1  3 15]
 [ 0  0  0  0  0  0  0  1  6]
 [ 0  0  0  0  0  0  0  0  1]]
[[1 3 1 4 3 0 4 2 2]
 [0 1 3 4 3 0 0 0 3]
 [0 0 1 4 3 4 4 1 0]
 [0 0 0 1 3 0 4 4 0]
 [0 0 0 0 1 3 2 2 0]
 [0 0 0 0 0 1 0 1 2]
 [0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 1 4]
 [0 0 0 0 0 0 0 0 1]]
[[1 5 1 3 3 4 8 1 5]
 [0 1 9 1 6 8 7 8 9]
 [0 0 1 6 8 3 2 4 8]
 [0 0 0 1 2 8 9 7 2]
 [0 0 0 0 1 4 4 4 1]
 [0 0 0 0 0 1 0 8 3]
 [0 0 0 0 0 0 1 6 0]
 [0 0 0 0