## CIS242 Homework #9 (Due Apr 10, 10pm)

Remember to make a copy of this notebook before you start to work, and rename the notebook to be **"CIS242_Spring2023_Homework#_Name"**.

Rule #1: please finish all required problems first and then optional bonus problems that you finish all in one notebook. Then share the notebook with anyone with link, and **submit the link to Canvas** for me to grade.

Rule #2: **please finish all coding work by yourself as much as you can**. Since exams are real-time coding, overly seeking help from others may risk underdeveloping your independent coding skills and thus underperformance in exams.

Rule #3: **For any function that you write, it should have proper docstrings to explain what your function does, what are acceptable inputs for each argument, and what is the returning value of the function**.

===========================================

## Homework Problem:

a) Write a function `my_LU_part1_4by4(A)` that returns the upper triangular matrix $U$ in the LU decomposition of a $4\times 4$ matrix A if $A$ is invertible and there is no zero at the main diagonal during the Gaussian elimination (you don't need to do row switching).

In [ ]:
import numpy as np
import scipy.linalg as la

n = 4

A0 = np.random.randint(1, 10, (n, n))
A0 = A0.astype(float)
print(A0)

# Make sure that A0 is invertible
print(la.det(A0))

[[2. 3. 2. 8.]
 [9. 9. 2. 5.]
 [5. 4. 1. 2.]
 [8. 6. 8. 4.]]
339.9999999999999


In [ ]:
def my_LU_part1_4by4(A: np.ndarray) -> np.ndarray:
  """
  Returns the upper triangular matrix  U  in the LU decomposition of a 4×4 
  matrix A if A is invertible and there is no zero at the main diagonal during 
  the Gaussian elimination (you don't need to do row switching).

  Parameters
  ----------
  A: np.ndarray
    Numpy array of 4x4 dimension.

  Returns
  -------
  np.ndarray
    Upper traingular matrix of 4x4. 

  Raises
  -------
  TypeError
      If A is not a square matrix of 4x4 dimension.
      If A is not Numpy array.
  """
  assert isinstance(A, np.ndarray) is True
  if A.shape[0] != A.shape[1] != 4: raise TypeError 
  
  A0 = A.copy()
  # We will update A from now on following steps of Gaussian Elimination
  # COLUMN 1
  A0[[1], :] = A0[[1], :] + (-A0[1, 0]/A0[0, 0]) * A0[[0], :]
  A0[[2], :] = A0[[2], :] + (-A0[2, 0]/A0[0, 0]) * A0[[0], :]
  A0[[3], :] = A0[[3], :] + (-A0[3, 0]/A0[0, 0]) * A0[[0], :]

  #COLUMN 2
  A0[[2], :] = A0[[2], :] + (-A0[2, 1]/A0[1, 1]) * A0[[1], :]
  A0[[3], :] = A0[[3], :] + (-A0[3, 1]/A0[1, 1]) * A0[[1], :]

  # COLUMN 3
  A0[[3], :] = A0[[3], :] + (-A0[3, 2]/A0[2, 2]) * A0[[2], :]

  return A0

In [ ]:
my_LU_part1_4by4(A0)

array([[  2.        ,   3.        ,   2.        ,   8.        ],
       [  0.        ,  -4.5       ,  -7.        , -31.        ],
       [  0.        ,   0.        ,   1.44444444,   6.11111111],
       [  0.        ,   0.        ,   0.        , -26.15384615]])

In [ ]:
A_test = np.array([[2, -1, 2, -1], [2, -3, -2, -2], [-1, 2, -4, 1], [3, 0, 0, -3]])
my_LU_part1_4by4(A_test)

array([[ 2, -1,  2, -1],
       [ 0, -2, -4, -1],
       [ 0,  0, -5,  0],
       [ 0,  0,  0, -1]])

b) Write a function `my_LU_part1_nbyn(A)` that returns the upper triangular matrix $U$ in the LU decomposition of a general $n\times n$ matrix A if $A$ is invertible and there is no zero at the main diagonal during the Gaussian elimination (you don't need to do row switching).

You may use the following code the create a random $n\times n$ matrix with non-zero determinant for you to check your code.

In [ ]:
def my_LU_part1_nbyn(A: np.ndarray) -> np.ndarray:
  """
  Returns the upper triangular matrix  U  in the LU decomposition of a n×n 
  matrix A if A is invertible and there is no zero at the main diagonal during 
  the Gaussian elimination (you don't need to do row switching).

  Parameters
  ----------
  A: np.ndarray
    Numpy array of nxn dimension.

  Returns
  -------
  np.ndarray
    Upper traingular matrix of nxn. 

  Raises
  -------
  TypeError
      If A is not a square matrix of nxn dimension.
      If A is not Numpy array.
  """

  assert isinstance(A, np.ndarray) is True
  if A.shape[0] != A.shape[1]: 
    raise TypeError("Matrix needs to have be square matrix of nxn dimension.")
  
  A0 = A.copy()

  for i in range(1, len(A0)):
    for j in range(i, len(A0)):
      A0[[j], :] = A0[[j], :] + (-A0[j, i-1]/A0[i-1, i-1]) * A0[[i-1], :]


  return A0

In [ ]:
my_LU_part1_nbyn(A0)

array([[  2.        ,   3.        ,   2.        ,   8.        ],
       [  0.        ,  -4.5       ,  -7.        , -31.        ],
       [  0.        ,   0.        ,   1.44444444,   6.11111111],
       [  0.        ,   0.        ,   0.        , -26.15384615]])

In [ ]:
A_test = np.array([[2, -1, 2, -1], [2, -3, -2, -2], [-1, 2, -4, 1], [3, 0, 0, -3]])
my_LU_part1_nbyn(A_test)

array([[ 2, -1,  2, -1],
       [ 0, -2, -4, -1],
       [ 0,  0, -5,  0],
       [ 0,  0,  0, -1]])