## CIS242 Homework #10 (Due Apr 19, 10pm)

Remember to make a copy of this notebook before you start to work, and rename the notebook to be **"CIS242_Spring2023_Homework#_Name"**.

Rule #1: please finish all required problems first and then optional bonus problems that you finish all in one notebook. Then share the notebook with anyone with link, and **submit the link to Canvas** for me to grade.

Rule #2: **please finish all coding work by yourself as much as you can**. Since exams are real-time coding, overly seeking help from others may risk underdeveloping your independent coding skills and thus underperformance in exams.

Rule #3: **For any function that you write, it should have proper docstrings to explain what your function does, what are acceptable inputs for each argument, and what is the returning value of the function**.

===========================================

In [ ]:
import numpy as np
import scipy as sp
import sys
import random

## Homework Problem:

a) Write a function `my_LU(A)` that returns the upper triangular matrix $U$ and the lower triangular matrix $L$ in the LU decomposition of a general $n\times n$ matrix A if $A$ is invertible and there is no zero at the main diagonal during the Gaussian elimination (you don't need to do row switching). If $A$ is not square or there is zero at the main diagonal, return an appropriate error message.

In [ ]:
def my_LU(A: np.ndarray) -> np.ndarray:
  """
  Returns the upper triangular matrix U and the lower traingular matrix L in 
  the LU decomposition of a n×n matrix A if A is invertible and there is no zero 
  on the main diagonal during Gaussian elimination 
  (no row switching).

  Parameters
  ----------
  A: np.ndarray
    Numpy array of nxn dimension.

  Returns
  -------
  tuple: (np.ndarray, np.ndarray)
    Upper traingular matrix and lower triangular matrix 

  Raises
  -------
  TypeError
      If A is not a square matrix of nxn dimension.
      If A is not Numpy array.
      If A has zeroes on the main diagonal. 
  """

  if not isinstance(A, np.ndarray): raise TypeError('A must be Numpy array')
  if len(A) != A.shape[1]: raise TypeError('A must be square matrix')
  if not all(np.diag(A)) != 0.0: 
    print('Main Diagonal: ', np.diag(A))
    raise TypeError('A cannot have zeroes on its main diagonal')


  U = A.copy()
  n = U.shape[0]
  L = np.eye(n)

  for i in range(1, n):
    L[i:,[i-1]] = U[i:, [i-1]]/U[i-1,i-1]
    U[i:, :] = U[i:, :] - U[i:, [i-1]]/U[i-1,i-1] @U[[i-1],:]
  
  return L, U

In [ ]:
n=10
A0 = np.random.randint(1, 10, (n, n))
A0 = A0.astype(float)

my_LU(A0)

(array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 5.        ,  1.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 1.        , -0.08333333,  1.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 3.        ,  0.16666667,  1.        ,  1.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 4.        ,  0.75      ,  0.16666667, -0.28431373,  1.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 8.        ,  1.58333333,  1.5       ,  1.20588235, -6.97275204,
          1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 3.        ,  0.58333333, -0.5       , -0.20588235,  0.30245232,
          0.02630174,  1.       

In [ ]:
#Test Error Handling
n=10
A0 = np.random.randint(1, 10, (n, n))
A0 = A0.astype(float)
A0[0,0] = 0.0
print(A0)
print(all(np.diag(A0)) != 0.0)

my_LU(A0)

[[0. 5. 8. 7. 8. 2. 6. 7. 4. 5.]
 [1. 5. 7. 1. 1. 6. 2. 4. 3. 9.]
 [5. 7. 7. 8. 4. 6. 1. 8. 4. 3.]
 [1. 9. 8. 1. 3. 8. 3. 9. 6. 2.]
 [1. 2. 4. 1. 9. 3. 3. 5. 9. 1.]
 [1. 4. 8. 8. 7. 3. 2. 4. 2. 4.]
 [9. 1. 2. 5. 1. 1. 8. 5. 2. 9.]
 [4. 1. 2. 6. 6. 6. 2. 3. 5. 1.]
 [7. 3. 6. 9. 2. 3. 7. 8. 6. 6.]
 [8. 1. 6. 5. 6. 8. 2. 1. 8. 2.]]
False
Main Diagonal:  [0. 5. 7. 1. 9. 3. 8. 3. 6. 2.]


TypeError: ignored

b) Write a function `my_det(A)` that returns the determinant of an $n\times n$ matrix using LU decomposition and the fact that the determinant of a triangular matrix is equal to the product of all entries on the main diagonal. Again, when LU decomposition fails for your code, return an error message.

In [ ]:
def my_det(A: np.ndarray) -> np.ndarray:
  """
  Returns the determinant of an nxn matrix using LU decomposition and the fact 
  that determinants of triangular matricies are equal to the product of all its 
  entries on its main diagonal. 

  Parameters
  ----------
  A: np.ndarray
    Numpy array of nxn dimension.

  Returns
  -------
  float
    Determinant

  Raises
  -------
  TypeError
    If A is not a square matrix of nxn dimension.
    If A is not Numpy array.
    If A has zeroes on the main diagonal. 

  Exception
    If LU decomposition fails
  """
  try:
    L, U = my_LU(A)
  except KeyboardInterrupt as e:
    print(e)
    sys.exit(0)
  except Exception as e:
    print("LU decomposition failed because of ", e)
    sys.exit(1)

  return np.prod(np.diag(L)) * np.prod(np.diag(U))

In [ ]:
n=10
A0 = np.random.randint(1, 10, (n, n))
A0 = A0.astype(float)

print(np.linalg.det(A0))
my_det(A0)

20400276.00000003


20400276.000000015

## Bonus Problem (50% Bonus)

Read the textbook to understand how to do LU decomposition with row switching. Write a function `my_LU2(A)` that can do LU decomposition with row switching. In that case, the product of $LU$ should be different from the original matrix only by row switching.

In [ ]:
def my_LU2(A: np.ndarray) -> np.ndarray:
  """
  Returns the upper triangular matrix U and the lower traingular matrix L in 
  the LU decomposition of a n×n matrix A if A is invertible (uses row switching).

  Parameters
  ----------
  A: np.ndarray
    Numpy array of nxn dimension.

  Returns
  -------
  tuple: (np.ndarray, np.ndarray)
    Upper traingular matrix and lower triangular matrix 

  Raises
  -------
  TypeError
      If A is not a square matrix of nxn dimension.
      If A is not Numpy array.
  """

  if not isinstance(A, np.ndarray): raise TypeError('A must be Numpy array')
  if len(A) != A.shape[1]: raise TypeError('A must be square matrix')
  if all(np.diag(A)) != 0.0: return my_LU(A)

  U = A.copy()

  rows_with_zeroes = set()
  rows_without_zeroes = set()
  for index, val in enumerate(np.diag(A)):
    if val == 0 or val == 0.0: rows_with_zeroes.add(index)
    else: rows_without_zeroes.add(index)


  for i in rows_with_zeroes:

    for row_index in range(len(U)):
      if U[row_index, i] != 0 and row_index not in rows_with_zeroes:
        U[[i, row_index]] = U[[row_index, i]]

  print("Rows with zeroes: ", rows_with_zeroes)
  print('U matrix after row switching')
  print(U)

  n = U.shape[0]
  L = np.eye(n)

  for i in range(1, n):
    L[i:,[i-1]] = U[i:, [i-1]]/U[i-1,i-1]
    U[i:, :] = U[i:, :] - U[i:, [i-1]]/U[i-1,i-1] @U[[i-1],:]
  
  return L, U

In [ ]:
n=10
A0 = np.random.randint(0, 10, (n, n))
A0 = A0.astype(float)
A0[0,0] = 0.0
A0[1,1] = 0.0
print("Matrix before row switching")
print(A0)

my_LU2(A0)

Matrix before row switching
[[0. 2. 2. 6. 6. 5. 8. 3. 6. 5.]
 [9. 0. 2. 3. 1. 4. 3. 2. 3. 8.]
 [0. 3. 6. 8. 2. 8. 0. 5. 6. 0.]
 [6. 8. 4. 4. 5. 8. 4. 4. 3. 9.]
 [4. 0. 1. 3. 5. 2. 6. 5. 9. 2.]
 [3. 8. 8. 3. 8. 7. 3. 7. 1. 3.]
 [8. 7. 7. 2. 5. 2. 3. 0. 9. 5.]
 [7. 9. 3. 3. 4. 1. 7. 3. 8. 5.]
 [7. 2. 7. 8. 1. 1. 5. 7. 3. 3.]
 [3. 3. 6. 9. 2. 3. 2. 6. 8. 0.]]
[0. 0. 6. 4. 5. 7. 3. 3. 3. 0.]
[7. 6. 5. 4. 3. 3. 3. 0. 0. 0.]
Rows with zeroes:  {0, 1, 9}
U matrix after row switching
[[7. 2. 7. 8. 1. 1. 5. 7. 3. 3.]
 [7. 9. 3. 3. 4. 1. 7. 3. 8. 5.]
 [3. 3. 6. 9. 2. 3. 2. 6. 8. 0.]
 [0. 3. 6. 8. 2. 8. 0. 5. 6. 0.]
 [9. 0. 2. 3. 1. 4. 3. 2. 3. 8.]
 [0. 2. 2. 6. 6. 5. 8. 3. 6. 5.]
 [4. 0. 1. 3. 5. 2. 6. 5. 9. 2.]
 [6. 8. 4. 4. 5. 8. 4. 4. 3. 9.]
 [3. 8. 8. 3. 8. 7. 3. 7. 1. 3.]
 [8. 7. 7. 2. 5. 2. 3. 0. 9. 5.]]


(array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 1.        ,  1.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.42857143,  0.30612245,  1.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.42857143,  1.82608696,  1.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 1.28571429, -0.36734694, -2.00483092, -1.81025641,  1.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.28571429,  0.74396135, -0.75897436,  3.40841248,
          1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.57142857, -0.16326531, -0.8647343 , -1.32820513,  3.84803256,
          1.08754198,  1.       

# Teacher Comments

Good job!
Bonus +5